{
  "headers": {
    "host": "localhost:8081",
    "connection": "keep-alive",
    "sec-ch-ua": "\"\\\\Not;A\\\"Brand\";v=\"99\", \"Google Chrome\";v=\"85\", \"Chromium\";v=\"85\"",
    "sec-ch-ua-mobile": "?0",
    "upgrade-insecure-requests": "1",
    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36",
    "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
    "sec-fetch-site": "none",
    "sec-fetch-mode": "navigate",
    "sec-fetch-user": "?1",
    "sec-fetch-dest": "document",
    "accept-encoding": "gzip, deflate, br",
    "accept-language": "en-US,en;q=0.9",
    "cookie": "jenkins-timestamper-offset=-19800000; ACEGI_SECURITY_HASHED_REMEMBER_ME_COOKIE=c2FuZGVlcHRoaXBwYXJlZGR5OjE2MDMxMzQ4MzExMzc6YjUwMjFkOTQ3M2RkZWFkN2RmNmJlNmEwYmI1ODllOTU5MzgzNDlmZTdlZTJkOGI2YzE0YjgwNTBjOGI0ZmRjOA==; JSESSIONID.e74b6dbf=node01vuqm5jfu2j3gkug3c0zz24u1.node0; screenResolution=1536x864"
  },
  "clientCertificate": null,
  "method": "GET",
  "scheme": "http",
  "queryParams": {},
  "requestUri": "/timezone/dummy",
  "queryString": "",
  "version": "HTTP/1.1",
  "maskedRequestPath": null,
  "listenerPath": "/timezone/dummy",
  "relativePath": "/dummy",
  "localAddress": "/127.0.0.1:8081",
  "uriParams": {},
  "rawRequestUri": "/timezone/dummy",
  "rawRequestPath": "/timezone/dummy",
  "remoteAddress": "/127.0.0.1:57668",
  "requestPath": "/timezone/dummy"
}